### PR TITLE
Use new GA workflow

### PR DESCRIPTION
**Pull request by alb3rtino**
Lets try the new GA workflow.

@zburke @ncovercash

### CODE REVIEW

**Comment by ncovercash** [comment]
@alb3rtino do you need me/Zak to override the CI check so this can be merged?

**Comment by alb3rtino** [comment]
Yes. Please.
And may I ask why this is even necessary?

**Comment by ncovercash** [comment]
The override or the new workflows?

**Comment by alb3rtino** [comment]
The override.

**Comment by ncovercash** [comment]
GH is setup to require the old workflow before merging, so it's looking for that (called `github-actions-ci`). Since the new workflows have different parts and names, it isn't finding the old one, so we have to change the check

**Review by ncovercash — APPROVED** [review]

**Comment by alb3rtino** [comment]
So its about branch protection rules? Would it just work if the new workflow was named `github-actions-ci` instead of `ui`?

Still cant merge btw.

**Comment by ncovercash** [comment]
Unfortunately no, since the new ones have the multiple steps (and repos could check for `Run jest tests`, `Run bigtest tests`, etc each as applicable.

I'm waiting on permissions, I sent a message in #devops on slack

**Comment by alb3rtino** [comment]
Ok. Thanks! I just wish there was an easier way to handle this without needing to trouble anyone.

**Pull request merged**
