### PR TITLE
UIEUS-366: Detail-view-cutted-off

### PR DESCRIPTION
**Pull request by elsenhans**
https://folio-org.atlassian.net/browse/UIEUS-366

### CODE REVIEW

**Review by alb3rtino — CHANGES_REQUESTED** [review]
Sorry, but I can not reproduce the described problem. To me it seems like we're trying to fix things that are not broken here. I also think we should not make any changes to the styling provided by stripes components unless we absolutely have to.

**Comment by elsenhans** [comment]
Did you use Chrome? I am using Version 127.0.6533.119 
The problem can be reproduced with Chrome here: https://testing.dev.folio.finc.info/

**Comment by alb3rtino** [comment]
I can not reproduce it with chrome version `128.0.6613.84`. Is the problem present in other apps as well?

**Comment by alb3rtino** [comment]
[Screencast from 26.08.2024 10:52:30.webm](https://github.com/user-attachments/assets/fb6c6a0c-61c9-45e9-b237-d11408581543)

What am I missing?

**Comment by elsenhans** [comment]
You are not missing anything. If I am or Stefan is doing the same, the detail view is cutted like in the image here: https://folio-org.atlassian.net/browse/UIEUS-366

**Pull request closed without merging**
